//! Editor command enumeration

use crate::editor::EditorMode;
use super::Direction;

/// Represents all possible commands that can be issued in the editor
///
/// Commands are generated by the input handler based on key events
/// and the current editor mode. They represent high-level actions
/// that the editor should perform.
///
/// # Examples
///
/// ```
/// use termide::input::{EditorCommand, Direction};
/// use termide::editor::EditorMode;
///
/// // Character insertion
/// let cmd = EditorCommand::InsertChar('a');
///
/// // Cursor movement
/// let cmd = EditorCommand::MoveCursor(Direction::Up);
///
/// // Mode switching
/// let cmd = EditorCommand::ChangeMode(EditorMode::Normal);
///
/// // File operations
/// let cmd = EditorCommand::Save;
/// let cmd = EditorCommand::Quit;
/// ```
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EditorCommand {
    /// Insert a character at the current cursor position
    InsertChar(char),

    /// Delete the character before the cursor (backspace)
    DeleteChar,

    /// Move the cursor in the specified direction
    MoveCursor(Direction),

    /// Save the current buffer to file
    Save,

    /// Quit the editor
    Quit,

    /// Change the editor mode
    ChangeMode(EditorMode),
}
